### ISSUE TITLE
Content is not immediately editable on iOS

### ISSUE THREAD

**Issue by chmac** [chmac/cohesion-catalyst#4]
Steps to reproduce:

* Create a new node on iOS
* Type on the keyboard

Expected result

* Text should update

Actual result

* Text does not update

Workaround

* Tapping anywhere else or on the node itself
* Now editing works

**Comment by chmac** [comment]
@hschirmacher I eventually found a workaround, by creating a fake input. This works on my iPad in my test right now. But I'm running the latest iOS release, not sure what your tablets are running...

**Comment by hschirmacher** [comment]
Works perfectly now! :-)
