### ISSUE TITLE
Text inserts in front of placeholder

### ISSUE THREAD

**Issue by chmac** [chmac/cohesion-catalyst#6]
* Instead of `I identify with` being replaced, new text gets inserted before it

> There are some timing issues with the app though that I have never noticed before. The one especially related to the input screen is that if you quickly drag a new bubble out of the head and then immediately start typing, sometimes he dummy text "I identify with" does not get deleted, but the text you type gets inserted in front of it.

**Comment by chmac** [comment]
@hschirmacher I wasn't able to reproduce this in my testing. Can you reproduce it with any consistency? Maybe there's something about your setup which I can try to replicate...

**Comment by hschirmacher** [comment]
I have not sees this when testing in the actual production environment. So I suggest we close this until it happens again.
